# Generated by Django 5.0.6 on 2024-05-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=20, unique=True, verbose_name='Codigo Asonaproyuca')),
            ],
        ),
    ]
